"""Immutable content and transactional draft metadata boundaries."""

from typing import Protocol

from clearcut.domain.screenplay import ContentReference, Draft, Revision


class ScreenplayContent(Protocol):
    def put(
        self, organization_id: str, project_id: str, content_id: str, data: bytes
    ) -> ContentReference: ...
    def get(self, reference: ContentReference) -> bytes: ...


class DraftStore(Protocol):
    def get_draft(self, project_id: str) -> Draft | None: ...
    def save(
        self, project_id: str, expected_version: int, content: ContentReference, actor: str, at: str
    ) -> Draft: ...
    def freeze(self, project_id: str, expected_version: int, actor: str, at: str) -> Revision: ...
    def revision(self, project_id: str, revision_id: str) -> Revision: ...
    def revisions(self, project_id: str, before_version: int | None = None) -> list[Revision]: ...
