"""Identity verification and authorization storage boundaries."""

from typing import Protocol

from clearcut.domain.identity import Identity
from clearcut.domain.project import Project


class IdentityVerifier(Protocol):
    def verify(self, token: str) -> Identity: ...


class ProjectAccess(Protocol):
    def authorize(self, user_id: str, project_id: str, action: str) -> str:
        """Return organization ID only after active membership and explicit grant."""
        ...

    def visible_project_ids(self, user_id: str) -> set[str]: ...
    def get_project(self, project_id: str) -> Project: ...
    def create_project(self, user_id: str, organization_id: str, project: Project) -> None: ...
    def create_organization(self, user_id: str, organization_id: str, name: str) -> None: ...
    def organizations(self, user_id: str) -> list[dict[str, str]]: ...


class OwnedFiles(Protocol):
    def register_file(self, project_id: str, file_id: str, uri: str) -> None: ...
    def resolve_file(self, project_id: str, file_id: str) -> str: ...
